const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs/promises')
const path = require('node:path')
const crypto = require('node:crypto')

test('开放接口真实 HTTP/PostgreSQL：授权、并发、回滚、历史、附件、旧入口兼容', {skip:process.env.OPEN_API_INTEGRATION !== '1'}, async () => {
  const schema = `open_api_test_${crypto.randomBytes(8).toString('hex')}`
  // 测试仅使用随机隔离 schema，不读写现有业务数据。
  process.env.DB_OPTIONS = `-c search_path=${schema} -c timezone=Asia/Shanghai`
  const db = require('../src/db')
  const express = require('express')
  const { createOpenApiService } = require('../src/services/openApiService')
  const { createOpenApiRouter } = require('../src/routes/openApi')
  const { hash } = require('../src/services/openApiContract')
  let server
  try {
    await db.exec(`CREATE SCHEMA ${schema}`)
    const init = (await fs.readFile(path.join(__dirname,'../db/init/001_schema.sql'),'utf8')).replace(/^ALTER (DATABASE|ROLE).*$/gm,'')
    await db.exec(init)
    const user = await db.prepare('SELECT id,employee_no FROM pms_user WHERE is_deleted=0 ORDER BY id LIMIT 1').get()
    const role = await db.prepare('SELECT id FROM pms_role ORDER BY id LIMIT 1').get()
    await db.prepare('INSERT INTO pms_user_role(user_id,role_id) VALUES(?,?) ON CONFLICT DO NOTHING').run(user.id,role.id)
    await db.exec('INSERT INTO pms_role_menu(role_id,menu_id) SELECT ?,id FROM pms_menu ON CONFLICT DO NOTHING',[role.id])
    const product = await db.prepare('INSERT INTO pms_product(name,owner_id) VALUES(?,?)').run('开放接口测试产品',user.id)
    const problem = await db.prepare("SELECT a.code FROM pms_archive a JOIN pms_archive_type t ON t.id=a.archive_type_id WHERE t.code_prefix='PT' AND a.status=1 LIMIT 1").get()
    const token = `sidm_open_${crypto.randomBytes(32).toString('base64url')}`
    // 空旧白名单也能调用全部已开放业务，仍保留实际人员权限检查。
    const client = await db.prepare('INSERT INTO pms_open_client(code,name,token_hash,enabled) VALUES(?,?,?,1)').run('test','测试',hash(token))
    let uploads = 0
    const service = createOpenApiService({db,upload:async (file) => {
      uploads++
      return {storageName:`pmis/test/${uploads}.txt`,ossResponse:{data:[{id:'test',fileName:file.originalname,filePath:`pmis/test/${uploads}.txt`,fileUrl:`http://oss.znjs.com:9000/pmis/test/${uploads}.txt`}]}}
    }})
    const { importMappings } = require('../scripts/open-api-import-i8')
    const app = express()
    app.use(express.json())
    const {verifyToken} = require('../src/middleware/auth')
    const {checkPermission} = require('../src/middleware/checkPermission')
    app.use('/api/integrations',verifyToken,checkPermission('/integrations'),require('../src/routes/integration'))
    app.use('/api/open-clients',verifyToken,checkPermission('/integrations'),require('../src/routes/openClientAdmin'))
    let downloadFails = false
    app.use('/api/open/v1',createOpenApiRouter({service,download:async () => {
      if (downloadFails) throw new Error('storage unavailable')
      return new Response('文件内容')
    }}))
    // 旧页面控制器仍可按原方式访问。
    const old = require('../src/controllers/requirementController')
    app.get('/legacy/:id',(req,res) => old.getById(req,res))
    server = app.listen(0,'127.0.0.1')
    await new Promise((resolve) => server.once('listening',resolve))
    const origin = `http://127.0.0.1:${server.address().port}`
    // 管理页接口真实 JWT/会话/菜单授权，独立系统凭证不能用于管理接口。
    const {recordLoginSuccess} = require('../src/services/accessLogService')
    const jwt = require('jsonwebtoken')
    await db.prepare('UPDATE pms_user SET first_login=0 WHERE id=?').run(user.id)
    const sessionId = await recordLoginSuccess({user,account:user.employee_no,req:{headers:{},ip:'127.0.0.1'}})
    const adminToken = jwt.sign({userId:Number(user.id),employeeNo:user.employee_no,sessionId},process.env.JWT_SECRET,{expiresIn:'5m'})
    const admin = async (suffix,method = 'GET',body,credential = adminToken) => {
      const response = await fetch(`${origin}/api/open-clients${suffix}`,{method,headers:{authorization:`Bearer ${credential}`,'content-type':'application/json'},...(body ? {body:JSON.stringify(body)} : {})})
      return {status:response.status,cache:response.headers.get('cache-control'),...await response.json()}
    }
    assert.equal((await admin('','GET',undefined,token)).status,401)
    const adminConfig = {name:'页面接入系统',expiresAt:null}
    const managed = await admin('','POST',adminConfig)
    assert.equal(managed.code,0,JSON.stringify(managed))
    const managedId = managed.data.id
    assert.equal(managed.data.updated_by,null)
    assert.equal(managed.data.enabled,0)
    assert.equal(Number(managed.data.created_by),Number(user.id))
    assert.equal(Object.hasOwn(managed.data,'token_hash'),false)
    assert.equal(managed.data.code,`SYS${String(managed.data.id).padStart(6,'0')}`)
    const anotherManaged = await admin('','POST',adminConfig)
    assert.notEqual(anotherManaged.data.code,managed.data.code)
    const concurrentClients = await Promise.all(Array.from({length:4},() => admin('','POST',adminConfig)))
    assert.ok(concurrentClients.every((r) => r.code === 0))
    assert.equal(new Set(concurrentClients.map((r) => r.data.code)).size,4)
    assert.equal((await admin(`/${managedId}`,'PUT',{...adminConfig,code:'changed'})).status,400)
    assert.equal((await admin(`/${managedId}`,'PUT',{...adminConfig,name:'新名称'})).code,0)
    assert.equal(Number((await admin(`/${managedId}`)).data.updated_by),Number(user.id))
    assert.ok((await admin(`/${managedId}`)).data.updater_name)
    const nameAudit = await db.prepare("SELECT * FROM pms_op_log WHERE module='接入系统' AND target_id=? AND action='编辑'").all(managedId)
    assert.equal(nameAudit[0].field_name,'系统名称')
    assert.equal(nameAudit[0].old_value,adminConfig.name)
    assert.equal(nameAudit[0].new_value,'新名称')
    assert.ok(nameAudit[0].operation_id)
    const changedConfig = {...adminConfig,name:'新名称',expiresAt:new Date(Date.now()+86400000).toISOString()}
    assert.equal((await admin(`/${managedId}`,'PUT',changedConfig)).code,0)
    const authorizationAudit = await db.prepare("SELECT * FROM pms_op_log WHERE module='接入系统' AND target_id=? AND action='编辑' AND field_name<>'系统名称'").all(managedId)
    assert.equal(authorizationAudit.length,1)
    assert.equal(new Set(authorizationAudit.map((r) => r.operation_id)).size,1)
    assert.equal(authorizationAudit[0].field_name,'凭证有效期')
    await admin(`/${managedId}`,'PUT',changedConfig)
    assert.equal(Number((await db.prepare("SELECT COUNT(*) total FROM pms_op_log WHERE module='接入系统' AND target_id=? AND action='编辑'").get(managedId)).total),2)
    await admin(`/${managedId}`,'PUT',{...adminConfig,name:'新名称'})
    const credentialOne = await admin(`/${managedId}/credential`,'POST')
    assert.equal(Number((await admin(`/${managedId}`)).data.updated_by),Number(user.id))
    assert.equal(credentialOne.cache,'no-store')
    assert.match(credentialOne.data.credential,/^sidm_open_/)
    await admin(`/${managedId}/status`,'PATCH',{enabled:1})
    assert.equal(Number((await admin(`/${managedId}`)).data.updated_by),Number(user.id))
    await service.authenticate(credentialOne.data.credential)
    const credentialTwo = await admin(`/${managedId}/credential`,'POST')
    assert.notEqual(credentialOne.data.credential,credentialTwo.data.credential)
    await assert.rejects(() => service.authenticate(credentialOne.data.credential))
    await service.systemQuery(credentialTwo.data.credential,'HEALTH')
    const managedHistory = await admin(`/${managedId}/requests?page=1&pageSize=1&outcome=success`)
    assert.equal(managedHistory.data.total,1)
    assert.equal(managedHistory.data.list[0].operation,'HEALTH')
    assert.equal((await service.systemQuery(credentialTwo.data.credential,'REFERENCE_DATA',user.employee_no,['users'])).code,0)
    await service.systemQuery(credentialTwo.data.credential,'REFERENCE_DATA','not-exists',['users'])
    assert.match((await admin(`/${managedId}/requests?outcome=failed`)).data.list[0].message,/操作人不存在/)
    assert.equal((await admin(`/${managedId}`)).data.code,managed.data.code)
    assert.equal((await admin(`/${managedId}`)).data.name,'新名称')
    const savedHash = (await db.prepare('SELECT token_hash FROM pms_open_client WHERE id=?').get(managedId)).token_hash
    assert.equal(JSON.stringify((await admin('')).data).includes(savedHash),false)
    await admin(`/${managedId}/status`,'PATCH',{enabled:0})
    const updaterSnapshot = await admin(`/${managedId}`)
    assert.equal(Number(updaterSnapshot.data.updated_by),Number(user.id))
    await admin(`/${managedId}/status`,'PATCH',{enabled:0})
    assert.equal((await admin(`/${managedId}`)).data.updated_at,updaterSnapshot.data.updated_at)
    // 模拟旧数据：有精确匹配的日志才回填，无更新事件的记录保持空值。
    await db.prepare('UPDATE pms_open_client SET updated_by=NULL WHERE id=?').run(managedId)
    const updaterMigration = await fs.readFile(path.join(__dirname,'../db/migrations/20260907_02_open_client_updater.sql'),'utf8')
    await db.exec(updaterMigration)
    assert.equal(Number((await admin(`/${managedId}`)).data.updated_by),Number(user.id))
    assert.equal((await admin(`/${anotherManaged.data.id}`)).data.updated_by,null)
    await db.prepare("UPDATE pms_open_client SET updated_by=NULL,updated_at=updated_at+INTERVAL '1 second' WHERE id=?").run(managedId)
    await db.exec(updaterMigration)
    assert.equal((await admin(`/${managedId}`)).data.updated_by,null)
    await assert.rejects(() => service.authenticate(credentialTwo.data.credential))
    await db.prepare("UPDATE pms_open_client SET expires_at='2020-01-01' WHERE id=?").run(managedId)
    assert.match((await admin(`/${managedId}/status`,'PATCH',{enabled:1})).message,/凭证已过期/)
    const adminLogs = await db.prepare("SELECT action FROM pms_op_log WHERE module='接入系统' AND target_id=?").all(managedId)
    assert.ok(adminLogs.some((r) => r.action === '重置凭证'))
    await db.prepare('DELETE FROM pms_role_menu WHERE role_id=? AND menu_id IN (SELECT id FROM pms_menu WHERE path=?)').run(role.id,'/integrations')
    assert.equal((await admin('')).status,403)
    assert.equal((await admin(`/${managedId}/credential`,'POST')).status,403)
    await db.exec('INSERT INTO pms_role_menu(role_id,menu_id) SELECT ?,id FROM pms_menu ON CONFLICT DO NOTHING',[role.id])
    const call = async (resource,body,t = token) => {
      const r = await fetch(`${origin}/api/open/v1/${resource}/operate`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${t}`},body:JSON.stringify(body)})
      return {status:r.status,...await r.json()}
    }
    const input = {operation:'CREATE',sourceRecordId:'external-1',operatorEmployeeNo:user.employee_no,idempotencyKey:'create-1',data:{title:'开放测试需求',requirementType:4,productName:'开放接口测试产品',ownerEmployeeNo:user.employee_no,submitterName:'张三',submitDate:'2026-09-01'}}
    assert.equal((await call('requirements',input,'bad')).status,401)
    assert.equal((await call('requirements',{...input,operatorEmployeeNo:'not-exists'})).status,403)
    const simultaneous = await Promise.all([call('requirements',input),call('requirements',input)])
    assert.ok(simultaneous.every((r) => r.code === 0),JSON.stringify(simultaneous))
    assert.equal(simultaneous.filter((r) => r.data.replayed).length,1)
    const id = simultaneous[0].data.targetId
    assert.equal(Number((await db.prepare('SELECT COUNT(*) n FROM pms_requirement WHERE title=?').get(input.data.title)).n),1)
    const req = (operation,data,key = crypto.randomUUID()) => ({...input,operation,data,idempotencyKey:key})
    assert.equal((await call('requirements',req('UPDATE',{title:'其他'},'create-1'))).status,409)
    assert.equal((await call('requirements',req('UPDATE',{description:'更新说明'}))).code,0)
    assert.equal((await call('requirements',req('UPDATE',{description:'更新说明'}))).data.result,'SKIPPED')
    const q = await call('requirements',{operation:'QUERY',sourceRecordId:'external-1',operatorEmployeeNo:user.employee_no})
    assert.equal(q.code,0,JSON.stringify(q))
    assert.equal(q.data.title,'开放测试需求')
    assert.equal(q.data.priority,0)
    assert.equal(q.data.creator.employeeNo,user.employee_no)
    assert.ok(q.data.allowedStatuses.length)
    const reference = await fetch(`${origin}/api/open/v1/reference-data?types=products,users,workOrderProblemTypes&operatorEmployeeNo=${user.employee_no}`,{headers:{authorization:`Bearer ${token}`}})
    assert.equal(reference.status,200)
    assert.ok((await reference.json()).data.workOrderProblemTypes.length)
    // 相同工号持有另一系统凭证也不能查询不属于该系统的业务。
    const otherToken = `sidm_open_${crypto.randomBytes(32).toString('base64url')}`
    const other = await db.prepare('INSERT INTO pms_open_client(code,name,token_hash,enabled,scopes,operator_ids) VALUES(?,?,?,1,?,?)').run('other','另一系统',hash(otherToken),JSON.stringify(['requirement:QUERY']),JSON.stringify([Number(user.id)]))
    assert.equal((await call('requirements',{operation:'QUERY',sourceRecordId:'external-1',operatorEmployeeNo:user.employee_no},otherToken)).code,404)
    // 旧白名单不再限制操作；记录仍按接入系统隔离。
    assert.equal((await service.systemQuery(otherToken,'REFERENCE_DATA',user.employee_no,['users'])).code,0)
    // 人员自身权限被撤销后不能依靠系统授权继续调用。
    await db.prepare('DELETE FROM pms_role_menu WHERE role_id=? AND menu_id IN (SELECT id FROM pms_menu WHERE path=?)').run(role.id,'/requirements')
    assert.equal((await call('requirements',{operation:'QUERY',sourceRecordId:'external-1',operatorEmployeeNo:user.employee_no})).code,403)
    await db.exec('INSERT INTO pms_role_menu(role_id,menu_id) SELECT ?,id FROM pms_menu ON CONFLICT DO NOTHING',[role.id])
    const integration = await db.prepare('INSERT INTO pms_integration_config(code,name,adapter_code,endpoint_url,enabled) VALUES(?,?,?,?,1)').run('open_import_test','映射测试','i8_it_operations','http://unused.invalid')
    await db.prepare('INSERT INTO pms_integration_sync_record(integration_config_id,source_key,source_type,target_type,target_id,payload_hash,sync_status) VALUES(?,?,?,?,?,?,?)').run(integration.lastInsertRowid,'old-i8-record','需求问题','requirement',id,'a'.repeat(64),'success')
    assert.equal((await importMappings(Number(other.lastInsertRowid),Number(integration.lastInsertRowid))).ready.length,1)
    assert.equal(Number((await db.prepare('SELECT COUNT(*) n FROM pms_open_record WHERE client_id=?').get(other.lastInsertRowid)).n),0)
    await assert.rejects(() => importMappings(Number(other.lastInsertRowid),Number(integration.lastInsertRowid),{apply:true}),/先停用/)
    await db.prepare('UPDATE pms_integration_config SET enabled=0 WHERE id=?').run(integration.lastInsertRowid)
    assert.equal((await importMappings(Number(other.lastInsertRowid),Number(integration.lastInsertRowid),{apply:true})).applied,true)
    assert.equal((await importMappings(Number(other.lastInsertRowid),Number(integration.lastInsertRowid))).existing.length,1)
    const legacy = await (await fetch(`${origin}/legacy/${id}`)).json()
    assert.equal(legacy.data.description,'更新说明')
    const invalid = await call('requirements',req('CHANGE_STATUS',{status:999}))
    assert.equal(invalid.code,400)
    const history = await db.prepare("SELECT * FROM pms_op_log WHERE module='需求' AND target_id=? ORDER BY id").all(id)
    assert.ok(history.some((h) => h.action === '新增'))
    assert.equal(history.filter((h) => h.field_name === 'description').length,1)
    // 不同请求号争抢同一来源，也只能成功一次。
    const race = await Promise.all(['r1','r2'].map((k) => call('requirements',{...input,sourceRecordId:'race',idempotencyKey:k,data:{...input.data,title:'并发需求'}})))
    assert.equal(race.filter((r) => r.code === 0).length,1)
    assert.equal(race.filter((r) => r.code === 409).length,1)
    // 在控制器业务写入之后故意让成功回执失败，验证数据/历史/映射全部回滚。
    await db.exec("ALTER TABLE pms_open_request ADD CONSTRAINT test_receipt_failure CHECK (idempotency_key <> 'rollback-key' OR outcome <> 'success')")
    assert.equal((await call('requirements',{...input,sourceRecordId:'rollback-source',idempotencyKey:'rollback-key',data:{...input.data,title:'必须回滚'}})).code,500)
    assert.equal(Number((await db.prepare("SELECT COUNT(*) n FROM pms_requirement WHERE title='必须回滚'").get()).n),0)
    assert.equal(Number((await db.prepare("SELECT COUNT(*) n FROM pms_open_record WHERE source_record_id='rollback-source'").get()).n),0)
    await db.exec('ALTER TABLE pms_open_request DROP CONSTRAINT test_receipt_failure')
    const wo = {operation:'CREATE',sourceRecordId:'work-1',operatorEmployeeNo:user.employee_no,idempotencyKey:'wo-create',data:{problemDescription:'问题描述',productName:'开放接口测试产品',problemTypeCode:problem.code,followerEmployeeNo:user.employee_no,urgency:1,expectedResolveDate:'2026-09-08',submitterName:'李四',submitterDept:'信息部',submitTime:'2026-09-01'}}
    const wc = await call('work-orders',wo)
    assert.equal(wc.code,0,JSON.stringify(wc))
    const ws = await call('work-orders',{...wo,operation:'CHANGE_STATUS',idempotencyKey:'wo-finish',data:{status:2,resolveDate:'2026-09-02',resultDescription:'已解决'}})
    assert.equal(ws.code,0,JSON.stringify(ws))
    assert.ok((await db.prepare("SELECT id FROM pms_op_log WHERE module='运维工单' AND target_id=? AND action='状态变更'").get(wc.data.targetId)))
    const fileRequest = async () => {
      const form = new FormData()
      form.append('operatorEmployeeNo',user.employee_no)
      form.append('idempotencyKey','file-key')
      form.append('file',new Blob(['文件内容'],{type:'text/plain'}),'test.txt')
      return (await fetch(`${origin}/api/open/v1/requirements/external-1/attachments`,{method:'POST',headers:{authorization:`Bearer ${token}`},body:form})).json()
    }
    const f1 = await fileRequest()
    assert.equal(f1.code,0,JSON.stringify(f1))
    assert.equal((await fileRequest()).data.replayed,true)
    assert.equal(uploads,1)
    const deletion = await fetch(`${origin}/api/open/v1/requirements/external-1/attachments/delete`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({attachmentId:999999,operatorEmployeeNo:user.employee_no,idempotencyKey:'wrong-file'})})
    assert.equal(deletion.status,404)
    const down = await fetch(`${origin}/api/open/v1/requirements/external-1/attachments/${f1.data.attachment.id}/download?operatorEmployeeNo=${user.employee_no}`,{headers:{authorization:`Bearer ${token}`}})
    downloadFails = true
    const failedDownload = await fetch(`${origin}/api/open/v1/requirements/external-1/attachments/${f1.data.attachment.id}/download?operatorEmployeeNo=${user.employee_no}`,{headers:{authorization:`Bearer ${token}`}})
    assert.equal(failedDownload.status,502)
    const failedDownloadBody = await failedDownload.json()
    const downloadLog = await db.prepare('SELECT outcome,http_status FROM pms_open_request WHERE request_id=?').get(failedDownloadBody.requestId)
    assert.equal(downloadLog.outcome,'failed')
    assert.equal(downloadLog.http_status,502)
    downloadFails = false
    assert.equal(await down.text(),'文件内容')
    const no = await fetch(`${origin}/api/open/v1/work-orders/work-1/attachments/${f1.data.attachment.id}/download?operatorEmployeeNo=${user.employee_no}`,{headers:{authorization:`Bearer ${token}`}})
    assert.equal(no.status,404)
    const deletedFile = await fetch(`${origin}/api/open/v1/requirements/external-1/attachments/delete`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({attachmentId:f1.data.attachment.id,operatorEmployeeNo:user.employee_no,idempotencyKey:'delete-file'})})
    assert.equal(deletedFile.status,200)
    assert.ok(await db.prepare("SELECT id FROM pms_op_log WHERE target_id=? AND action='删除附件'").get(id))
    assert.equal((await call('requirements',req('DELETE',{}))).code,0)
    assert.equal((await call('requirements',req('DELETE',{}))).data.result,'ALREADY_DELETED')
    assert.equal((await call('requirements',{...input,idempotencyKey:'recreate'})).code,409)
    assert.equal(Number((await db.prepare("SELECT COUNT(*) n FROM pms_open_request WHERE outcome='failed'").get()).n) >= 5,true)
    await db.prepare('UPDATE pms_open_client SET enabled=0 WHERE id=?').run(client.lastInsertRowid)
    assert.equal((await call('requirements',input)).status,403)
    assert.ok(product.lastInsertRowid)
  } finally {
    if (server) {server.closeAllConnections();await new Promise((resolve) => server.close(resolve))}
    await db.exec(`DROP SCHEMA IF EXISTS ${schema} CASCADE`)
    await db.pool.end()
  }
})
