import { useEffect,useState } from'react';import{App}from'antd';import{useParams}from'react-router-dom';
import{DeleteConfirmAction,DetailMetaList,DetailNeighborNav,HistoryTimelineSection,PermissionButton,RichTextViewer,TemplateDetailPage,TemplateDetailSection,useDetailNeighbors,usePageReturnNavigation}from'../../../components/admin';
import{deleteRequirement,getRequirement,getRequirementHistory,getRequirementNeighbors,updateRequirementStatus}from'../../../api/requirementApi';import type{RequirementRecord,RequirementStatus}from'../types';import{requirementTypeLabels}from'../statusTransitions';import{renderRequirementOverdue,renderRequirementPriority}from'../helpers';import{renderRequirementStatus,RequirementStatusChangeAction}from'../components/RequirementStatusChangeAction';
const date=(value:any)=>value&&typeof value==='object'&&'format'in value?value.format('YYYY-MM-DD'):undefined;
export function RequirementDetailPage(){const {navigateWithReturn,returnToSource}=usePageReturnNavigation('/requirements'),params=useParams(),{message}=App.useApp();const[row,setRow]=useState<RequirementRecord>(),[history,setHistory]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notFound,setNotFound]=useState(false),[revision,setRevision]=useState(0);const neighbors=useDetailNeighbors({id:params.id,moduleKey:'requirement',routeBase:'/requirements',fetchNeighbors:getRequirementNeighbors});
 const load=()=>{if(!params.id)return;setLoading(true);setError('');Promise.all([getRequirement(params.id).then(setRow),getRequirementHistory(params.id).then(items=>setHistory(items.map(item=>({id:String(item.id),operator:item.operator,action:item.action,time:String(item.created_at).slice(0,19).replace('T',' '),changes:item.changes.map((change:any)=>({field:change.field_name,before:change.old_value,after:change.new_value}))}))))]).catch(loadError=>{const text=loadError instanceof Error?loadError.message:'加载失败';if(text.includes('不存在'))setNotFound(true);else setError(text)}).finally(()=>setLoading(false))};useEffect(load,[params.id,revision]);
 const submitStatus=async(status:RequirementStatus,values:any)=>{await updateRequirementStatus(row!.id,status,status===35?{pause_date:date(values.pauseDate)}:[33,34].includes(status)?{actual_end_date:date(values.actualEndDate),completion_status:values.completionStatus}:{});message.success('状态更新成功');load()};
 return <TemplateDetailPage title="需求详情" loading={loading} error={error} notFound={notFound} onRetry={()=>setRevision(value=>value+1)} onBack={returnToSource} titleCenter={<DetailNeighborNav placement="title" loading={neighbors.loading} prevId={neighbors.prevId} nextId={neighbors.nextId} ordinal={neighbors.ordinal} total={neighbors.total} onNavigate={neighbors.navigateNeighbor}/>} actions={row?<><PermissionButton permission="requirement" type="primary" onClick={()=>navigateWithReturn(`/requirements/${row.id}/edit`)}>编辑</PermissionButton><PermissionButton permission="requirement" onClick={()=>navigateWithReturn(`/requirements/${row.id}/copy`)}>复制</PermissionButton><DeleteConfirmAction entityName="需求" targetName={row.title} successMessage="删除成功" onConfirm={async()=>{await deleteRequirement(row.id);returnToSource()}}>删除</DeleteConfirmAction></>:null}
 statusSection={row?{items:[{label:'当前状态',value:renderRequirementStatus(row.status),wide:true},{label:'优先级',value:renderRequirementPriority(row.priority),wide:true},{label:'逾期状态',value:row.isOverdue===null?'-':renderRequirementOverdue(row.isOverdue,row.expectedEndDate),wide:true}]}:null} statusAction={row?<RequirementStatusChangeAction block type="primary" requirement={row} onConfirm={submitStatus}/>:null} documentSection={row?{items:[{label:'创建人',value:row.creatorName},{label:'创建时间',value:row.createdAt,wide:true},{label:'更新人',value:row.updaterName},{label:'更新时间',value:row.updatedAt,wide:true}]}:null}>
 {row?<><TemplateDetailSection title="基本信息"><DetailMetaList items={[{label:'需求标题',value:row.title},{label:'需求描述',value:<RichTextViewer value={row.description}/>,wide:true},{label:'需求路径',value:requirementTypeLabels[row.requirementType]},{label:'所属产品',value:row.productName},{label:'所属项目',value:row.projectName}]}/></TemplateDetailSection>
 <TemplateDetailSection title="处理信息"><DetailMetaList items={[{label:'负责人',value:row.ownerName},{label:'提出人',value:row.submitterName},{label:'提出组织',value:row.submitterDept||'-'},{label:'提出时间',value:row.submitDate},{label:'启动时间',value:row.startDate||'-'},{label:'预计完成时间',value:row.expectedEndDate||'-'},{label:'实际完成时间',value:row.actualEndDate||'-'},{label:'暂停时间',value:row.pauseDate||'-'},{label:'完成情况',value:row.completionStatus||'-',wide:true,longText:true}]}/></TemplateDetailSection>
 <HistoryTimelineSection items={history}/></>:null}
 </TemplateDetailPage>}
