import { useEffect, useMemo, useState } from 'react';import { App } from 'antd';import { ProForm } from '@ant-design/pro-components';import { useParams } from 'react-router-dom';
import { AdminProFormDatePicker, AdminProFormRichDescription, AdminProFormSelect, AdminProFormText, TemplateFormPage, TemplateFormSection , usePageReturnNavigation } from '../../../components/admin';
import { createRequirement, getProjectOptions, getRequirement, updateRequirement } from '../../../api/requirementApi';import { getProductOptions } from '../../../api/productApi';import { getUserOptions } from '../../../api/userApi';import type { RequirementFormValues,RequirementStatus } from '../types';
export function RequirementFormPage({mode}:{mode:'create'|'edit'}){
 const {returnToSource}=usePageReturnNavigation('/requirements'),params=useParams(),{message}=App.useApp(),[form]=ProForm.useForm<RequirementFormValues>();const[products,setProducts]=useState<any[]>([]),[projects,setProjects]=useState<any[]>([]),[users,setUsers]=useState<any[]>([]),[initial,setInitial]=useState<Partial<RequirementFormValues>>(),[requirementStatus,setRequirementStatus]=useState<RequirementStatus>(),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notFound,setNotFound]=useState(false),[revision,setRevision]=useState(0);const productId=ProForm.useWatch('productId',form);const filteredProjects=useMemo(()=>projects.filter(project=>!productId||project.productId===productId),[projects,productId]);const requirementPathLocked=mode==='edit'&&requirementStatus!==undefined&&[30,31,32,33,34,35].includes(requirementStatus);
 useEffect(()=>{setLoading(true);Promise.all([getProductOptions().then(items=>setProducts(items.filter(item=>item.status===1))),getProjectOptions().then(setProjects),getUserOptions().then(setUsers),mode==='edit'&&params.id?getRequirement(params.id).then(row=>{setRequirementStatus(row.status);setInitial({title:row.title,description:row.description,requirementType:row.requirementType,productId:row.productId,projectId:row.projectId||undefined,ownerId:row.ownerId,priority:row.priority,submitterName:row.submitterName,submitterDept:row.submitterDept,submitDate:row.submitDate,startDate:row.startDate||undefined,expectedEndDate:row.expectedEndDate||undefined})}):Promise.resolve()]).catch(loadError=>{const text=loadError instanceof Error?loadError.message:'加载失败';text.includes('不存在')?setNotFound(true):setError(text)}).finally(()=>setLoading(false))},[mode,params.id,revision]);
 return <TemplateFormPage<RequirementFormValues> title={mode==='create'?'新增需求':'编辑需求'} formId="requirement-form" form={form} initialValues={initial} loading={loading} error={error} notFound={notFound} onRetry={()=>setRevision(value=>value+1)} onCancel={returnToSource} fieldNameMap={{requirement_type:'requirementType',product_id:'productId',project_id:'projectId',owner_id:'ownerId',submitter_name:'submitterName',submit_date:'submitDate'}} onSubmit={async values=>{mode==='create'?await createRequirement(values):params.id&&await updateRequirement(params.id,values);message.success(mode==='create'?'新增成功':'保存成功');returnToSource()}}>
  <TemplateFormSection title="基本信息"><div className="admin-template-form-page__grid">
   <AdminProFormText name="title" label="需求标题" rules={[{required:true,message:'请输入需求标题'}]} fieldProps={{maxLength:200}} formItemProps={{className:'admin-template-form-page__field is-full'}}/>
   <AdminProFormRichDescription name="description" label="需求描述" className="admin-template-form-page__field is-full"/>
   <AdminProFormSelect name="requirementType" label="需求路径" options={[{label:'上会立项',value:1},{label:'需求提报',value:2},{label:'预研',value:3},{label:'直接实施',value:4}]} rules={[{required:true,message:'请选择需求路径'}]} fieldProps={{disabled:requirementPathLocked}}/>
   <AdminProFormSelect name="productId" label="所属产品" options={products} rules={[{required:true,message:'请选择所属产品'}]} fieldProps={{onChange:()=>form.setFieldValue('projectId',undefined)}}/>
   <AdminProFormSelect name="projectId" label="所属项目" options={filteredProjects} fieldProps={{onChange:(value)=>{const project=projects.find(item=>item.value===value);if(project)form.setFieldValue('productId',project.productId)}}}/><AdminProFormSelect name="priority" label="优先级" options={[{label:'低',value:0},{label:'中',value:1},{label:'高',value:2}]} rules={[{required:true}]}/>
  </div></TemplateFormSection>
  <TemplateFormSection title="处理信息"><div className="admin-template-form-page__grid"><AdminProFormSelect name="ownerId" label="负责人" options={users} rules={[{required:true,message:'请选择负责人'}]}/><AdminProFormText name="submitterName" label="提出人" rules={[{required:true,message:'请输入提出人'}]}/><AdminProFormText name="submitterDept" label="提出组织"/><AdminProFormDatePicker name="submitDate" label="提出时间" rules={[{required:true,message:'请选择提出时间'}]}/><AdminProFormDatePicker name="startDate" label="启动时间"/><AdminProFormDatePicker name="expectedEndDate" label="预计完成时间"/></div></TemplateFormSection>
 </TemplateFormPage>
}
