import { useEffect, useState } from 'react';
import { App } from 'antd';
import { ProForm } from '@ant-design/pro-components';
import { useParams } from 'react-router-dom';
import { AdminProFormSelect,AdminProFormText,AdminProFormTextArea,TemplateFormPage,TemplateFormSection , usePageReturnNavigation } from '../../../components/admin';
import { createProduct,getProduct,updateProduct } from '../../../api/productApi';
import { getUserOptions } from '../../../api/userApi';
import type { ProductFormValues } from '../types';
export function ProductFormPage({mode}:{mode:'create'|'edit'}){const {returnToSource}=usePageReturnNavigation('/products'),params=useParams(),{message}=App.useApp(),[form]=ProForm.useForm<ProductFormValues>();const [users,setUsers]=useState<Array<{label:string;value:string}>>([]),[initial,setInitial]=useState<Partial<ProductFormValues>>(),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notFound,setNotFound]=useState(false),[rev,setRev]=useState(0);useEffect(()=>{setLoading(true);Promise.all([getUserOptions().then(setUsers),mode==='edit'&&params.id?getProduct(params.id).then(r=>setInitial({name:r.name,ownerId:r.ownerId,description:r.description,status:r.status})):Promise.resolve()]).catch(e=>{const t=e instanceof Error?e.message:'加载失败';t.includes('不存在')?setNotFound(true):setError(t)}).finally(()=>setLoading(false))},[mode,params.id,rev]);return <TemplateFormPage<ProductFormValues> title={mode==='create'?'新增产品':'编辑产品'} formId="product-form" form={form} initialValues={initial} loading={loading} error={error} notFound={notFound} onRetry={()=>setRev(v=>v+1)} onCancel={returnToSource} onSubmit={async v=>{mode==='create'?await createProduct(v):params.id&&await updateProduct(params.id,v);message.success(mode==='create'?'新增成功':'保存成功');returnToSource()}}><TemplateFormSection title="基本信息"><div className="admin-template-form-page__grid"><AdminProFormText name="name" label="产品名称" rules={[{required:true,message:'请输入产品名称'}]} fieldProps={{maxLength:100}}/><AdminProFormSelect name="ownerId" label="负责人" options={users} rules={[{required:true,message:'请选择负责人'}]}/><AdminProFormTextArea name="description" label="产品描述" fieldProps={{rows:4,maxLength:1000}} formItemProps={{className:'admin-template-form-page__field is-full'}}/></div></TemplateFormSection></TemplateFormPage>}
