import dayjs from'dayjs';import{request,unwrap}from'./requestClient';import{arrayContract,objectContract}from'./responseContract';import type{RequirementFormValues,RequirementRecord,RequirementStatus,RequirementType,RequirementPriority}from'../modules/requirement/types';
type Row={id:number;title:string;description?:string;requirement_type:number;product_id:number;product_name:string;project_id?:number;project_name?:string;owner_id:number;owner_name:string;priority:number;status:number;previous_status?:number;is_overdue:number|null;submitter_name:string;submitter_dept?:string;submit_date:string;start_date?:string;expected_end_date?:string;actual_end_date?:string;pause_date?:string;completion_status?:string;creator_name?:string;updater_name?:string;created_at?:string;updated_at?:string};
const rowContract=objectContract<Row>(['id','title','requirement_type','product_id','product_name','owner_id','owner_name','priority','status','submitter_name','submit_date']);const pageContract=objectContract<any>(['list','total','page','pageSize','viewCounts'],{list:arrayContract(rowContract)});const idContract=objectContract<{id:number}>(['id']);const historyContract=arrayContract(objectContract<any>(['id','action','created_at','operator','changes']));const d=(v?:string)=>String(v||'').slice(0,10),dt=(v?:string)=>String(v||'').slice(0,19).replace('T',' ');
const map=(r:Row):RequirementRecord=>({id:String(r.id),title:r.title,description:r.description||'',requirementType:Number(r.requirement_type)as RequirementType,productId:String(r.product_id),productName:r.product_name,projectId:r.project_id?String(r.project_id):'',projectName:r.project_name||'-',ownerId:String(r.owner_id),ownerName:r.owner_name,priority:Number(r.priority)as RequirementPriority,status:Number(r.status)as RequirementStatus,previousStatus:r.previous_status===undefined?undefined:Number(r.previous_status)as RequirementStatus,isOverdue:r.is_overdue===null?null:Boolean(Number(r.is_overdue)),submitterName:r.submitter_name,submitterDept:r.submitter_dept||'',submitDate:d(r.submit_date),startDate:d(r.start_date),expectedEndDate:d(r.expected_end_date),actualEndDate:d(r.actual_end_date),pauseDate:d(r.pause_date),completionStatus:r.completion_status||'',creatorName:r.creator_name||'-',updaterName:r.updater_name||'-',createdAt:dt(r.created_at),updatedAt:dt(r.updated_at)});
export async function getRequirementList(params:Record<string,unknown>={}){const r=await unwrap<any>(request.get('/requirements',{params}),pageContract);return{...r,list:r.list.map(map)}}export async function getRequirement(id:string){return map(await unwrap<Row>(request.get(`/requirements/${id}`),rowContract))}
const date=(v?:string)=>v?dayjs(v).format('YYYY-MM-DD'):null;const payload=(v:RequirementFormValues)=>({title:v.title,description:v.description||null,requirement_type:Number(v.requirementType),product_id:Number(v.productId),project_id:v.projectId?Number(v.projectId):null,owner_id:Number(v.ownerId),priority:Number(v.priority),submitter_name:v.submitterName,submitter_dept:v.submitterDept||null,submit_date:date(v.submitDate),start_date:date(v.startDate),expected_end_date:date(v.expectedEndDate)});
export async function createRequirement(v:RequirementFormValues){return unwrap<{id:number}>(request.post('/requirements',payload(v)),idContract)}export async function updateRequirement(id:string,v:RequirementFormValues){return unwrap<null>(request.put(`/requirements/${id}`,payload(v)))}export async function updateRequirementStatus(id:string,status:RequirementStatus,extra={}){return unwrap<null>(request.put(`/requirements/${id}/status`,{status,...extra}))}export async function deleteRequirement(id:string){return unwrap<null>(request.delete(`/requirements/${id}`))}export async function getRequirementHistory(id:string){return unwrap<any[]>(request.get(`/requirements/${id}/history`),historyContract)}
const neighborsContract=objectContract<{prevId:number|null;nextId:number|null;ordinal?:number;total?:number}>(['prevId','nextId']);export async function getRequirementNeighbors(id:string,params:Record<string,unknown>={}){const r=await unwrap<{prevId:number|null;nextId:number|null;ordinal?:number;total?:number}>(request.get('/requirements/neighbors',{params:{...params,id}}),neighborsContract);return{prevId:r.prevId===null?null:String(r.prevId),nextId:r.nextId===null?null:String(r.nextId),ordinal:r.ordinal,total:r.total}}
const projectOptionContract=arrayContract(objectContract<{id:number;name:string;product_id:number}>(['id','name','product_id']));export async function getProjectOptions(){const r=await unwrap<Array<{id:number;name:string;product_id:number}>>(request.get('/projects/options'),projectOptionContract);return r.map(x=>({label:x.name,value:String(x.id),productId:String(x.product_id)}))}
