const router = require('express').Router()
const controller = require('../controllers/bugController')
const richTextImage = require('../controllers/richTextImageController')
const { uploadRichTextImage } = require('../middleware/richTextImageUpload')
const { uploadBusinessAttachment } = require('../middleware/businessAttachmentUpload')
const { createBusinessAttachmentController } = require('../controllers/businessAttachmentController')
const attachment = createBusinessAttachmentController('bug')

router.get('/', controller.list)
router.get('/neighbors', controller.neighbors)
router.get('/project-options', controller.projectOptions)
router.get('/requirement-options', controller.requirementOptions)
router.get('/check-title', controller.checkTitle)
router.put('/batch-assign', controller.batchAssign)
router.post('/rich-text-images', uploadRichTextImage, richTextImage.upload)
router.get('/:id/attachments', attachment.list)
router.post('/:id/attachments', uploadBusinessAttachment, attachment.upload)
router.get('/:id/attachments/:attachmentId/download', attachment.download)
router.delete('/:id/attachments/:attachmentId', attachment.remove)
router.get('/:id/history', controller.history)
router.get('/:id', controller.getById)
router.post('/', controller.create)
router.put('/:id', controller.update)
router.put('/:id/status', controller.toggleStatus)
router.delete('/:id', controller.remove)

module.exports = router
