const express = require('express')
const multer = require('multer')
const ctrl = require('../controllers/productController')
const contractCtrl = require('../controllers/productMaintenanceContractController')
const { MAX_ATTACHMENT_SIZE } = require('../services/projectContractAttachmentService')
const { fail } = require('../utils/response')
const router = express.Router()
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: MAX_ATTACHMENT_SIZE } })
const uploadAttachment = (req, res, next) => upload.single('file')(req, res, (error) => {
  if (!error) return next()
  if (error.code === 'LIMIT_FILE_SIZE') return fail(res, 400, 400, '单个附件不能超过20MB')
  return fail(res, 400, 400, '附件上传失败')
})
const uploadContractAttachments = (req, res, next) => upload.array('files', 10)(req, res, (error) => {
  if (!error) return next()
  if (error.code === 'LIMIT_FILE_SIZE') return fail(res, 400, 400, '单个附件不能超过20MB')
  return fail(res, 400, 400, '附件上传失败')
})
router.get('/options', ctrl.options)
router.get('/', ctrl.list)
router.get('/:id/maintenance-contracts', contractCtrl.list)
router.post('/:id/maintenance-contracts', uploadContractAttachments, contractCtrl.create)
router.get('/:id/maintenance-contracts/:contractId', contractCtrl.getById)
router.put('/:id/maintenance-contracts/:contractId', contractCtrl.update)
router.put('/:id/maintenance-contracts/:contractId/terminate', contractCtrl.terminate)
router.delete('/:id/maintenance-contracts/:contractId', contractCtrl.remove)
router.post('/:id/maintenance-contracts/:contractId/attachments', uploadAttachment, contractCtrl.uploadAttachment)
router.get('/:id/maintenance-contracts/:contractId/attachments/:attachmentId/download', contractCtrl.downloadAttachment)
router.delete('/:id/maintenance-contracts/:contractId/attachments/:attachmentId', contractCtrl.deleteAttachment)
router.get('/:id/history', ctrl.history)
router.get('/:id', ctrl.getById)
router.post('/', ctrl.create)
router.put('/:id', ctrl.update)
router.put('/:id/status', ctrl.toggleStatus)
router.delete('/:id', ctrl.remove)
module.exports = router
