const express = require('express')
const multer = require('multer')
const ctrl = require('../controllers/projectController')
const contractCtrl = require('../controllers/projectContractController')
const planCtrl = require('../controllers/projectStagePlanController')
const { MAX_ATTACHMENT_SIZE } = require('../services/projectContractAttachmentService')
const { fail } = require('../utils/response')
const router = express.Router()
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: MAX_ATTACHMENT_SIZE } })
const uploadAttachment = (req, res, next) => upload.single('file')(req, res, (error) => {
  if (!error) return next()
  if (error.code === 'LIMIT_FILE_SIZE') return fail(res, 400, 400, '单个附件不能超过20MB')
  return fail(res, 400, 400, '附件上传失败')
})
const uploadDelivery = (req, res, next) => upload.single('file')(req, res, (error) => {
  if (!error) return next()
  if (error.code === 'LIMIT_FILE_SIZE') return fail(res, 400, 400, '单个交付文件不能超过20MB')
  return fail(res, 400, 400, '交付文件上传失败')
})
const uploadStatusDelivery = (req, res, next) => upload.array('files')(req, res, (error) => {
  if (!error) return next()
  if (error.code === 'LIMIT_FILE_SIZE') return fail(res, 400, 400, '单个交付文件不能超过20MB')
  return fail(res, 400, 400, '交付文件上传失败')
})
router.get('/', ctrl.list)
router.get('/options', ctrl.options)
router.get('/:projectId/stage-plan', planCtrl.getPlan)
router.get('/:projectId/stage-plan/history', planCtrl.history)
router.post('/:projectId/stage-plan/stages', planCtrl.createStage)
router.put('/:projectId/stage-plan/stages/reorder', planCtrl.reorderStages)
router.put('/:projectId/stage-plan/stages/:stageId', planCtrl.updateStage)
router.delete('/:projectId/stage-plan/stages/:stageId', planCtrl.deleteStage)
router.post('/:projectId/stage-plan/items', planCtrl.createItem)
router.post('/:projectId/stage-plan/items/batch', planCtrl.createItems)
router.put('/:projectId/stage-plan/stages/:stageId/items/reorder', planCtrl.reorderItems)
router.put('/:projectId/stage-plan/items/:itemId', planCtrl.updateItem)
router.put('/:projectId/stage-plan/items/:itemId/status', uploadStatusDelivery, planCtrl.changeStatus)
router.post('/:projectId/stage-plan/items/:itemId/adjustments', planCtrl.createAdjustment)
router.get('/:projectId/stage-plan/items/:itemId/adjustments', planCtrl.listAdjustments)
router.delete('/:projectId/stage-plan/items/:itemId', planCtrl.deleteItem)
router.get('/:projectId/stage-plan/items/:itemId/files', planCtrl.listFiles)
router.post('/:projectId/stage-plan/items/:itemId/files', uploadDelivery, planCtrl.uploadFile)
router.delete('/:projectId/stage-plan/items/:itemId/files/:fileId', planCtrl.deleteFile)
router.get('/:projectId/stage-plan/items/:itemId/files/:fileId/download', planCtrl.downloadFile)
router.get('/:id/contract', contractCtrl.getByProject)
router.post('/:id/contract', contractCtrl.create)
router.put('/:id/contract', contractCtrl.update)
router.delete('/:id/contract', contractCtrl.remove)
router.post('/:id/contract/attachments', uploadAttachment, contractCtrl.uploadAttachment)
router.get('/:id/contract/attachments/:attachmentId/download', contractCtrl.downloadAttachment)
router.delete('/:id/contract/attachments/:attachmentId', contractCtrl.deleteAttachment)
router.get('/:id/contract/stages/:stageId/payments', contractCtrl.listPayments)
router.post('/:id/contract/stages/:stageId/payments', contractCtrl.createPayment)
router.put('/:id/contract/payments/:paymentId', contractCtrl.updatePayment)
router.delete('/:id/contract/payments/:paymentId', contractCtrl.deletePayment)
router.get('/:id/history', ctrl.history)
router.get('/:id', ctrl.getById)
router.post('/', ctrl.create)
router.put('/:id', ctrl.update)
router.put('/:id/status', ctrl.toggleStatus)
router.delete('/:id', ctrl.remove)
module.exports = router
