const express = require('express')
const ctrl = require('../controllers/projectController')
const contractCtrl = require('../controllers/projectContractController')
const router = express.Router()
router.get('/', ctrl.list)
router.get('/options', ctrl.options)
router.get('/:id/contract', contractCtrl.getByProject)
router.post('/:id/contract', contractCtrl.create)
router.put('/:id/contract', contractCtrl.update)
router.get('/:id/contract/stages/:stageId/payments', contractCtrl.listPayments)
router.post('/:id/contract/stages/:stageId/payments', contractCtrl.createPayment)
router.put('/:id/contract/payments/:paymentId', contractCtrl.updatePayment)
router.delete('/:id/contract/payments/:paymentId', contractCtrl.deletePayment)
router.get('/:id/history', ctrl.history)
router.get('/:id', ctrl.getById)
router.post('/', ctrl.create)
router.put('/:id', ctrl.update)
router.put('/:id/status', ctrl.toggleStatus)
router.delete('/:id', ctrl.remove)
module.exports = router
