const express = require('express')
const ctrl = require('../controllers/requirementController')
const richTextImage = require('../controllers/richTextImageController')
const { uploadRichTextImage } = require('../middleware/richTextImageUpload')
const { uploadBusinessAttachment } = require('../middleware/businessAttachmentUpload')
const { createBusinessAttachmentController } = require('../controllers/businessAttachmentController')
const attachment = createBusinessAttachmentController('requirement')
const { checkPermissionCode } = require('../middleware/checkPermission')
const followUpController = require('../controllers/followUpRecordController')
const router = express.Router()
const followUps = followUpController.forTarget('requirement')
router.get('/', ctrl.list)
router.get('/neighbors', ctrl.neighbors)
router.post('/rich-text-images', uploadRichTextImage, richTextImage.upload)
router.get('/:id/follow-ups', followUps.list)
router.post('/:id/follow-ups', followUps.create)
router.put('/:id/follow-ups/:followUpId', followUps.update)
router.delete('/:id/follow-ups/:followUpId', followUps.remove)
router.get('/:id/attachments', attachment.list)
router.post('/:id/attachments', uploadBusinessAttachment, attachment.upload)
router.get('/:id/attachments/:attachmentId/download', attachment.download)
router.delete('/:id/attachments/:attachmentId', attachment.remove)
router.get('/:id/history', ctrl.history)
router.get('/:id', ctrl.getById)
router.post('/', ctrl.create)
router.put('/:id', ctrl.update)
router.put('/:id/priority', checkPermissionCode('requirement_priority_adjust'), ctrl.updatePriority)
router.put('/:id/status', ctrl.toggleStatus)
router.delete('/:id', ctrl.remove)
module.exports = router
