const express = require('express')
const ctrl = require('../controllers/requirementController')
const richTextImage = require('../controllers/richTextImageController')
const { uploadRichTextImage } = require('../middleware/richTextImageUpload')
const router = express.Router()
router.get('/', ctrl.list)
router.get('/neighbors', ctrl.neighbors)
router.post('/rich-text-images', uploadRichTextImage, richTextImage.upload)
router.get('/:id/history', ctrl.history)
router.get('/:id', ctrl.getById)
router.post('/', ctrl.create)
router.put('/:id', ctrl.update)
router.put('/:id/status', ctrl.toggleStatus)
router.delete('/:id', ctrl.remove)
module.exports = router
