const router = require('express').Router()
const controller = require('../controllers/taskController')
const richTextImage = require('../controllers/richTextImageController')
const { uploadRichTextImage } = require('../middleware/richTextImageUpload')
const { checkPermissionCode } = require('../middleware/checkPermission')
const followUpController = require('../controllers/followUpRecordController')
const followUps = followUpController.forTarget('task')
const { uploadBusinessAttachment } = require('../middleware/businessAttachmentUpload')
const { createBusinessAttachmentController } = require('../controllers/businessAttachmentController')
const attachment = createBusinessAttachmentController('task')

router.get('/', controller.list)
router.get('/neighbors', controller.neighbors)
router.get('/project-options', controller.projectOptions)
router.get('/requirement-options', controller.requirementOptions)
router.get('/check-name', controller.checkName)
router.put('/batch-assign', controller.batchAssign)
router.put('/batch-priority', checkPermissionCode('task_priority_adjust'), controller.batchUpdatePriority)
router.post('/rich-text-images', uploadRichTextImage, richTextImage.upload)
router.get('/:id/attachments', attachment.list)
router.post('/:id/attachments', uploadBusinessAttachment, attachment.upload)
router.get('/:id/attachments/:attachmentId/download', attachment.download)
router.delete('/:id/attachments/:attachmentId', attachment.remove)
router.get('/:id/subtasks', controller.listSubtasks)
router.post('/:id/subtasks', controller.createSubtask)
router.get('/:id/follow-ups', followUps.list)
router.post('/:id/follow-ups', followUps.create)
router.put('/:id/follow-ups/:followUpId', followUps.update)
router.delete('/:id/follow-ups/:followUpId', followUps.remove)
router.get('/:id/history', controller.history)
router.get('/:id', controller.getById)
router.post('/', controller.create)
router.put('/:id', controller.update)
router.put('/:id/priority', checkPermissionCode('task_priority_adjust'), controller.updatePriority)
router.put('/:id/status', controller.toggleStatus)
router.delete('/:id', controller.remove)

module.exports = router
