const express = require('express')
const router = express.Router()
const ctrl = require('../controllers/workOrderController')
const richTextImage = require('../controllers/richTextImageController')
const { uploadRichTextImage } = require('../middleware/richTextImageUpload')
const { uploadBusinessAttachment } = require('../middleware/businessAttachmentUpload')
const { createBusinessAttachmentController } = require('../controllers/businessAttachmentController')
const attachment = createBusinessAttachmentController('work_order')

router.get('/', ctrl.list)
router.get('/neighbors', ctrl.getNeighbors)
router.post('/refresh-overdue', ctrl.refreshOverdue)
router.put('/batch-assign', ctrl.batchAssign)
router.post('/rich-text-images', uploadRichTextImage, richTextImage.upload)
router.get('/:id/attachments', attachment.list)
router.post('/:id/attachments', uploadBusinessAttachment, attachment.upload)
router.get('/:id/attachments/:attachmentId/download', attachment.download)
router.delete('/:id/attachments/:attachmentId', attachment.remove)
router.get('/:id', ctrl.getById)
router.post('/', ctrl.create)
router.put('/:id', ctrl.update)
router.put('/:id/status', ctrl.toggleStatus)
router.delete('/:id', ctrl.remove)
router.get('/:id/history', ctrl.getHistory)

module.exports = router
